import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations);

  static List<String> languages() => ['en', 'te', 'hi', 'ta', 'kn', 'ml'];

  String get languageCode => locale.languageCode;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.languageCode] ?? '';

  String getVariableText({
    String enText = '',
    String teText = '',
    String hiText = '',
    String taText = '',
    String knText = '',
    String mlText = '',
  }) =>
      [enText, teText, hiText, taText, knText, mlText][languageIndex] ?? '';
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      FFLocalizations.languages().contains(locale.languageCode);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    'u9wjog6z': {
      'en': 'Home',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'y06426sc': {
      'en': 'Speciality ',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '1ndtnjd7': {
      'en': 'Explore',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'xgjbie3k': {
      'en': 'Partners',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'qn16rwok': {
      'en': 'Signup',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'hv03miap': {
      'en': 'LogIn',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'snq85egz': {
      'en': 'Advanced\nMedical Skills\nat your \nfingertips',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'fmquz5lu': {
      'en': '400k Alumni',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'nisfo46e': {
      'en': '190+ Countries',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'vglajg1f': {
      'en': '200+ Courses',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'e9vvbrvj': {
      'en': '250+ Instructors',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '1qfljzq5': {
      'en': 'Search Here',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'r7wppjz3': {
      'en': 'Simulations',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'jwywedxl': {
      'en': 'Online Events',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'mi7xdw1k': {
      'en': 'Contact \nProgram',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'fc1b9ead': {
      'en': 'Events &\nWebinars',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'mhkhm03n': {
      'en': 'Trending Courses',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'vja1oq6s': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '0tq00vnb': {
      'en': 'Featured',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'vb8dun32': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'xd4fbgcg': {
      'en': 'Simulation',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'jykcuwnh': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'btjcr41k': {
      'en': 'Contact Program',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ob17iygb': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'cmz40wxs': {
      'en': 'Live Video Classes',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'hodv0usq': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'n76yz201': {
      'en': 'Events',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'xv4c2h4m': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'n7s4ib6l': {
      'en': 'An Immersive Learning Experience',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'znvwyu6p': {
      'en': 'Select a course that you require',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'e03o0aj3': {
      'en': 'Select date & time to\nbook counselling',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'g8de2z3q': {
      'en': 'Understand the curriculum\nand know the course',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ru8512a6': {
      'en': 'Get Certification from\nMedvaristy & Apply for Jobs',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'b2b5h9c1': {
      'en': 'Why choose us?\n',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ux7cr3cf': {
      'en':
          'Amet minim mollit non deserunt ullamco est sit aliqua dolor  do amet sint. Velit officia consequat duis enim velit mollit. ',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'yyc4a5br': {
      'en': 'Certification Ready',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'bb4yo5l9': {
      'en': 'Select a course that you require',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '3o90s5ip': {
      'en': 'Contact Program',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'uf0p322t': {
      'en': 'Understand the curriculum\nand know the course',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '8kdzxvov': {
      'en': 'Gamification',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'zyo1qp49': {
      'en': 'Get Certification from\nMedvaristy & Apply for Jobs',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'uvhcmtvm': {
      'en': 'Simulation Program',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'glrufj2y': {
      'en': 'Select a course that you require',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'utran3mm': {
      'en': 'Accurate Reports',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '83x6wys7': {
      'en': 'Understand the curriculum\nand know the course',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '92itkvvq': {
      'en': 'Best Course Prices',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'gqmmflo9': {
      'en': 'Get Certification from\nMedvaristy & Apply for Jobs',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'r0ws0yrp': {
      'en': 'Numbers that matter',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '6kdfni5f': {
      'en': '10000+',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ciyofkkf': {
      'en': 'Courses Completed',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'uwjkhrgn': {
      'en': '1980+',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ovzk7gt9': {
      'en': 'Happy customers',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'c6eoqbpu': {
      'en': '700',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'fg6uhshp': {
      'en': 'Certified Instructors',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'yw1miu0y': {
      'en': '100+',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ejgkstor': {
      'en': 'Certifications',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'rp21iayu': {
      'en': 'Testimonials',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'zmbm5bun': {
      'en': 'Efficient Collaborating',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '12weapqv': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor neque sed imperdiet nibh lectus feugiat nunc sem.',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ije36i4x': {
      'en': 'Theresa Webb',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '2s8mhbwv': {
      'en': 'Manager - Engineering',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'i0tysmti': {
      'en': 'Efficient Collaborating',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'arhkglo4': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor neque sed imperdiet nibh lectus feugiat nunc sem.',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'talhls5f': {
      'en': 'Theresa Webb',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'kjk15ew3': {
      'en': 'Manager - Engineering',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'xp12tfr7': {
      'en': 'Efficient Collaborating',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'rlpe6bvf': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor neque sed imperdiet nibh lectus feugiat nunc sem.',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'mt8n3l5g': {
      'en': 'Theresa Webb',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'v3tooxif': {
      'en': 'Manager - Engineering',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'bm9q6kf6': {
      'en': 'For queries, feedback & assistance (7 AM - 12 AM)',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'cp4j7hk6': {
      'en': 'Medvarsity Support',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'x1x8n6eg': {
      'en': 'Request Call back',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'iawk2jai': {
      'en': 'Frequently asked questions',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'gaeez261': {
      'en': 'Course related',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ilv4w3mi': {
      'en': 'Lorem ipsum dolor sit amet, consectetur adipiscing...',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '5tu81vbc': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'otmw4qjs': {
      'en': 'Course related',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'f9usgamr': {
      'en': 'Lorem ipsum dolor sit amet, consectetur adipiscing...',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'he5bi3zt': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '1kble61d': {
      'en': 'Course related',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'jxodw3dh': {
      'en': 'Lorem ipsum dolor sit amet, consectetur adipiscing...',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'w5n78mcl': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'dswlcf4v': {
      'en': 'Invite your friends',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'h04hg2kh': {
      'en': 'Enroll for the best medvarsity courses and grow your skills',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'voglnhlk': {
      'en': 'INVITE NOW >',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '5gn54p5j': {
      'en': 'Categories',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '47s3vw23': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'xxfjf3ns': {
      'en': 'Explore',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'raxoj3ih': {
      'en': 'Simulations',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '6pq1j626': {
      'en': 'Online Events',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'yb3ie3ng': {
      'en': 'Contact Program',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'mrqwv1gb': {
      'en': 'Events & Webinars',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '9o90owp0': {
      'en': 'Trending Courses',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '51ei47g5': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '10bt72on': {
      'en': 'Simulations',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ofynf0i7': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'bwf11840': {
      'en': 'Request a call back from \nour team of expert\ncounsellors\n',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'aca0hevk': {
      'en': 'Request Call back',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '676t3y3o': {
      'en': 'Events',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'cui3ssg3': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ywreuvkw': {
      'en': 'Live Video Classes\n',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'of2w5yqw': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'p0kait8t': {
      'en': 'Contact Programs',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'h5c3rdio': {
      'en': 'View All',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'sgf7xpoc': {
      'en': 'Invite your friends',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '81ls5ob8': {
      'en': 'Enroll for the best medvarsity courses and grow your skills',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'u60dnng2': {
      'en': 'Share App',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'fcag06q6': {
      'en': 'Home',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // VideoScreen
  {
    'lhu0uhvg': {
      'en': 'Page Title',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '05qqi768': {
      'en': 'Home',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // Profile
  {
    'by18datg': {
      'en': 'Home',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // UserProfileWidget
  {
    'uh4ga8l6': {
      'en': 'Welcome',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '13yfsjgu': {
      'en': 'User Name',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // CourseCard
  {
    '9dyyp68a': {
      'en': 'Preview',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // BottomNavBar
  {
    '3jvk3j0c': {
      'en': 'Home',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '8qi0q52t': {
      'en': 'Home',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '3ibboxzt': {
      'en': 'Home',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // MiniCourseCard
  {
    'yfygmwyr': {
      'en': 'Preview',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // EventsCard
  {
    'nrcxi6we': {
      'en': 'Organized by',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // BottomNavBarHome
  {
    'jt49g8av': {
      'en': 'Home',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // BottomNavBarMyCourse
  {
    'ut2rqeyn': {
      'en': 'My Courses',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // BottomNavBarProfile
  {
    'sxi70wdc': {
      'en': 'Profile',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // tabName
  {
    '3b3ukxp8': {
      'en': 'Hello World',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // CourseCardWeb
  {
    '7rwp86x7': {
      'en': 'Preview',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // CourseCardWebFlex
  {
    '7wekstxc': {
      'en': 'Preview',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // EventsCardMini
  {
    'xyp7clx8': {
      'en': 'Organized by',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // webTesto
  {
    'zd8xgbmo': {
      'en': 'Efficient Collaborating',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'xxf4olw1': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor neque sed imperdiet nibh lectus feugiat nunc sem.',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '7omcsif1': {
      'en': 'Theresa Webb',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'geny7lt8': {
      'en': 'Manager - Engineering',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // AccordionItemComponent
  {
    'i9u5ya6u': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // footer
  {
    '8s1qvo7h': {
      'en': 'Learn free on the App',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '72dn6yxv': {
      'en':
          'Download the lessons and learn anytime, anywhere from\n the free courses available on our app',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'szxb8lh6': {
      'en': 'Scan this QR code on your camera app to download the app',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'rxnq6e9q': {
      'en': 'OR',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'rp1as1ca': {
      'en': 'Follow us',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'xkvjst31': {
      'en': 'Company',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'cgpydh8d': {
      'en': 'About Us',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'fw3cec7m': {
      'en': 'Careers',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'oto95fm3': {
      'en': 'In the media',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '3uyxy4wa': {
      'en': 'Alumni speak',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'q4jdyo2k': {
      'en': 'Contact  Us',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'za3qqzl7': {
      'en': 'Work with Us',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'jyc5yh0i': {
      'en': 'About Us',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'rb0y42gw': {
      'en': 'Careers',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'v1jynou8': {
      'en': 'In the media',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '4hpp7ksd': {
      'en': 'Alumni speak',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'c4is7km3': {
      'en': 'Contact  Us',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'bhm8jnpv': {
      'en': 'Discover',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'wugf4xf3': {
      'en': 'About Us',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '91y5hl34': {
      'en': 'Careers',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'h8wux89d': {
      'en': 'In the media',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'k0wpetjh': {
      'en': 'Alumni speak',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'voy2imd1': {
      'en': 'Contact  Us',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'obqnfku8': {
      'en': 'For Business',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'nftzirwd': {
      'en': 'About Us',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '2o04wdch': {
      'en': 'Careers',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'mswabjnk': {
      'en': 'In the media',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'u4m86qz4': {
      'en': 'Alumni speak',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'omvjelve': {
      'en': 'Contact  Us',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'muuoa31a': {
      'en': 'Learn On the Go!',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'unx9can0': {
      'en': 'Trending Post Graduate Programs',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'pc9a5rft': {
      'en':
          'PMP Plus Certification Training Course | Big Data Engineer Course | Data Science Certification Course | Data Analyst Certification Course | Artificial Intelligence Course | Cloud Architect Certification Training Course | DevOps Engineer Certification Training Course | Advanced Digital Marketing Course | Cyber Security Expert Course | MEAN Stack Developer Course',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '3ynrgnu8': {
      'en': 'Trending Post Graduate Programs',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '1noxtqou': {
      'en':
          'PMP Plus Certification Training Course | Big Data Engineer Course | Data Science Certification Course | Data Analyst Certification Course | Artificial Intelligence Course | Cloud Architect Certification Training Course | DevOps Engineer Certification Training Course | Advanced Digital Marketing Course | Cyber Security Expert Course | MEAN Stack Developer Course',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'e3bh644f': {
      'en': 'Trending Post Graduate Programs',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'jks6eyxf': {
      'en':
          'PMP Plus Certification Training Course | Big Data Engineer Course | Data Science Certification Course | Data Analyst Certification Course | Artificial Intelligence Course | Cloud Architect Certification Training Course | DevOps Engineer Certification Training Course | Advanced Digital Marketing Course | Cyber Security Expert Course | MEAN Stack Developer Course',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'isvnkzp1': {
      'en': 'Trending Post Graduate Programs',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '8wgaunfx': {
      'en':
          'PMP Plus Certification Training Course | Big Data Engineer Course | Data Science Certification Course | Data Analyst Certification Course | Artificial Intelligence Course | Cloud Architect Certification Training Course | DevOps Engineer Certification Training Course | Advanced Digital Marketing Course | Cyber Security Expert Course | MEAN Stack Developer Course',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'jtp82906': {
      'en': '• Terms of Use',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '4ydmxoah': {
      'en': '• Privacy Policy',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'rbek38cn': {
      'en': '• Refund Policy',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'w3winwj9': {
      'en': '• Reschedule Policy',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ldlypard': {
      'en': '• Country',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'qp1npmz8': {
      'en':
          '@ 2009-2021 - Simplilearn Solutions. All Rights Reserved. The certification names are the trademarks of their respective owners.\n',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // loginComponent
  {
    'd56yzdl5': {
      'en': 'Enter your mobile number to \nstart learning',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'nz43ikqk': {
      'en': 'Mobile Number',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '7psualww': {
      'en': 'Enter mobile number',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'otpx4p10': {
      'en': 'Remember Me',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'qg2et9ej': {
      'en': 'Send OTP',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'a43uzoc5': {
      'en': 'Enter your mobile number to \nstart learning',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '83grr5yy': {
      'en': 'Mobile Number',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '2ch7j7ua': {
      'en': 'Field is required',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'xucnh1sc': {
      'en': 'Please enter the OTP',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'aykozifu': {
      'en': 'Didnt recieve OTP ?',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'gm8vz1ef': {
      'en': 'Resend',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '985waojo': {
      'en': 'Log In',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'mcbsr4kb': {
      'en': 'Create Profile',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'behsb3c6': {
      'en': 'Add Personal Details',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'igh9gy1u': {
      'en': 'Add',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '8vsw6gzy': {
      'en': 'Personal Details',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'cvsm7phf': {
      'en': 'First Name*',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'gvbyu321': {
      'en': 'Last Name*',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '1uv9cezd': {
      'en': 'Email*',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'bajk6q9l': {
      'en': 'Option 1',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'v9lsnee5': {
      'en': 'Speciality*',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '0iu08dax': {
      'en': 'Skip',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'oayb0v9o': {
      'en': 'Save & Next',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'etc1jlkf': {
      'en': 'Create Profile',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'pomkqa4f': {
      'en': 'Select Preferences',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'jng0zk7y': {
      'en': 'Skip',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'ml7kzgzk': {
      'en': 'Save & Next',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'zrrozgmh': {
      'en': 'Create Profile',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'tqx97dyo': {
      'en': 'Select Preferences',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'h3juewij': {
      'en': 'Skip',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'b9w2bplo': {
      'en': 'Save & Next',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // actionbar
  {
    'jhmv6dig': {
      'en': 'Home',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '2oub1np0': {
      'en': 'Speciality ',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'duqblng8': {
      'en': 'Explore',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '063bpc11': {
      'en': 'Partners',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'sv3wgrhw': {
      'en': 'Signup',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'kw61ew99': {
      'en': 'LogIn',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
  // UserProfileWeb
  {
    '65ljml8g': {
      'en': 'Dr. John Meridian',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'dz8guwah': {
      'en': 'Pulmonologist',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '2s3pzvir': {
      'en': 'Credits Earned',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'dsh08mzk': {
      'en': '3200 credits',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    '389iu2s1': {
      'en': 'Total Points',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'mpggbpzs': {
      'en': '150 Points',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
    'g1kux8wz': {
      'en': 'Edit Profile',
      'hi': '',
      'kn': '',
      'ml': '',
      'ta': '',
      'te': '',
    },
  },
].reduce((a, b) => a..addAll(b));
